#!/bin/bash

# wrapper for jellyfish to output set of fasta-file-specific kmers 
# that are not present in a backgrout fasta-file
# input: two fasta files. each fasta file will be used as background
# for the other set
# $1 fasta file for set a, e.g. plastmid.fasta
# $2 fasta file for set b, e.g. chromosome.fasta

kmer_size=20
min_count=1

# get kmer binary
echo "calculate kmers for set a"
src/jellyfish-2.2.6/bin/jellyfish count -m $kmer_size \
  -s 100M -C $1 -o set_a -t 4 > /dev/null
  echo "calculate kmers for set a"
src/jellyfish-2.2.6/bin/jellyfish count -m $kmer_size \
  -s 100M -C $2 -o set_b -t 4 > /dev/null

# found plasmid unique
echo "extract background kmers of set b"
src/jellyfish-2.2.6/bin/jellyfish dump set_b -c | awk '{print $1}' | \
  sort --parallel=4 -S 50% > set_b_all.csv 
echo "extract abundant kmers of set a"
src/jellyfish-2.2.6/bin/jellyfish dump set_a -c --lower-count $min_count | \
  awk '{print $1}' | \
  sort  --parallel=4 -S 50% > set_a_high_abundant.csv

# found chr unique
echo "extract abundant kmers of set b"
src/jellyfish-2.2.6/bin/jellyfish dump set_b -c --lower-count $min_count | \
  awk '{print $1}' | sort  --parallel=4 -S 50% > set_b_high_abundant.csv 
echo "extract background kmers of set a"
src/jellyfish-2.2.6/bin/jellyfish dump set_a -c  | awk '{print $1}' | \
  sort --parallel=4 -S 50%  > set_a_all.csv

# get unique kmers of list
echo "write set a specific kmers to file set_a_specific.txt"
diff --new-line-format="" --unchanged-line-format="" \
  set_a_high_abundant.csv set_b_all.csv > set_a_specific.txt
echo "write set b specific kmers to file set_b_specific.txt"
diff --new-line-format="" --unchanged-line-format=""  \
  set_b_high_abundant.csv set_a_all.csv > set_b_specific.txt

#echo "delete intermediate files"
#rm -f set_a_high_abundant.csv set_b_high_abundant.csv \
#  set_a_all.csv set_b_all.csv \
#  set_a set_b

# you may want to check resulsts 
# src/jellyfish-2.2.6/bin/jellyfish query set_a AAATACGA
# src/jellyfish-2.2.6/bin/jellyfish query set_b AAATACGA